INSERT INTO MUSIC_STYLE (STYLE_ID, NAME) VALUES (1, 'Rock');
INSERT INTO MUSIC_STYLE (STYLE_ID, NAME) VALUES (2, 'Pop');
INSERT INTO MUSIC_STYLE (STYLE_ID, NAME) VALUES (3, 'Jazz');
INSERT INTO MUSIC_STYLE (STYLE_ID, NAME) VALUES (4, 'Classical');
INSERT INTO MUSIC_STYLE (STYLE_ID, NAME) VALUES (5, 'Electronic');

INSERT INTO USER_MUSIC_PREFERENCE(EMAIL, STYLE_ID) VALUES('eduardo@prueba.cl', 1);
INSERT INTO USER_MUSIC_PREFERENCE(EMAIL, STYLE_ID) VALUES('amanda@prueba.cl', 2);
